baseurl = "/"
languageCode = "en-us"
title = "MATH 4180"
theme = "hugo-PaperMod"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji= true

[permalinks]
    post = "/:slug/"
    
[[menu.main]]
    name = "Materials"
    url = "/materials/"
    weight = 1
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    
[[menu.main]]
    name = "People"
    url = "/people/"
    weight = 3
    
[params]
    description = "A website for MATH 4180 course at the University of Minnesota Duluth."

[params.homeInfoParams]
    Title = "Welcome to Industrial Problem Solving"
    Content = "This course introduces the full data cycle. Topics include data collection and retrieval, data cleaning, exploratory analysis and visualization, introduction to statistical modeling and inference, and communicating findings. Applications include real data from wide-range of fields following reproducible practices. "

[[params.socialIcons]]
    name = "other"
    url = "https://umn.zoom.us/j/99004362256?pwd=b0JPVjZvcjdZUjFYRU80V3I0cjA2Zz09" 
    
[[params.socialIcons]]
    name = "slack"
    url = "https://join.slack.com/t/math4180/shared_invite/zt-kl64pc6d-mdMu3edXjbUhSzg1c4g2Lw"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/kimchisquared/math4180"
    
[[params.socialIcons]]
    name = "other"
    url = "https://canvas.umn.edu/courses/206981" 

        
