baseurl = "/"
languageCode = "en-us"
title = "MATH 4180"
theme = "hugo-PaperMod"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji= true

[permalinks]
    post = "/:slug/"
    
[[menu.main]]
    name = "Materials"
    url = "/materials/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "People"
    url = "/people/"
    weight = 3
    
    
[params]
    description = "A website for MATH 4180 course at the University of Minnesota Duluth."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    #customCSS="css/font-awesome.min.css"    # path to the favicon, under "static"
    #favicon="logo.png"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

