---
title: 'Week 1: Getting Started'
author: Kim
date: '2021-01-07'
slug: week1
categories: []
tags: []
---



**Week 1 - Introduction to the Course and Data** <br> <br>
Welcome to the course! Before we start learning statistics we will get to know each other, the tools we will use, and the policies of the course. If you have any questions about Week 1 materials please post them on Slack (you will soon see what Slack is). If you click on icons such as it would direct you to the appropriate link where the course material lies.


| Tasks | Notes | Links |
| -------- | ------------- | ------ | 
| Getting to know the course website | Take time go over the contents of this website, especially read the policies section. Do not forget to bookmark [math4180.netlify.app](https://math4180.netlify.app/) | | 
| Sign up on Slack | | [&#9728;](https://join.slack.com/t/math4180/shared_invite/zt-kl64pc6d-mdMu3edXjbUhSzg1c4g2Lw) | | 
| Introduce yourself to your classmates | Post under the People channel in Slack. Include a paragraph or two about yourself and what you hope to learn from the course. | [&#9728;](https://join.slack.com/t/math4180/shared_invite/zt-kl64pc6d-mdMu3edXjbUhSzg1c4g2Lw) | 
| Add avatar and bio to Slack | Optional | | 
| Download and install R |  | [&#128279;](https://mirror.las.iastate.edu/CRAN/) [&#128214;](https://mdsr-book.github.io/mdsr2e/ch-R.html) | 
| Download and install R Studio | | [&#128279;](https://rstudio.com/products/rstudio/download/)[&#128214;](https://mdsr-book.github.io/mdsr2e/ch-R.html) |
| Customize RStudio theme | Optional | [&#128279;](https://blog.rstudio.com/2018/10/29/rstudio-ide-custom-theme-support/) |
| Sign up for WiDS conference | | [&#9728;](https://airtable.com/shrLE1J7hVxuYAILv) | |
| Sign up for Kaggle | This will bring you to the WiDS Datathon 2021 | [&#9728;](https://www.kaggle.com/c/widsdatathon2021) | |
| WiDS Datathon videos | Watch Video 1 and Video 2 | [&#128279;](https://www.widsconference.org/datathon-resources.html) | |
| Check out the swirl package | Optional R practice | [&#128279;](https://swirlstats.com/students.html) | |
| Reading from MDSR book |Chapter 1 | [&#128214;](https://mdsr-book.github.io/mdsr2e/ch-prologue.html) | |
| Sign up for Git | Use a username that is *semi* professional as we will use this platform to create personal websites later on in the semester. | [&#128279;](https://github.com/) | |
| Add avatar and bio to Github | Optional | | 
| Download Git | Windows users only | [&#128279;](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git/) | |
| What is the Question? | Optional Reading. Make sure to read the chart carefully. | [&#128214;](https://science.sciencemag.org/content/347/6228/1314.long) | |

