---
title: 'Week 2: Intro to Visualizing Data'
slug: data-viz-intro
weight: 20
---


**Grammar of Graphics & ggplot**\
\
This week we will be discussing what qualities makes a graphic legible and how we can use R to implement readability using the Grammar of Graphics.\
\

| Tasks | Notes | Links | Due |
| -------- | ------------- | ------ | ---- |
| | | | |
| Data Viz: intro | Slides | [:link:](/slides/data-viz-intro.html) | |
| Reading from MSDR book | Chapter 2: Data visualization. Post reading response (include one takeaway, one thing that would improve the reading, and any questions that you may have) in the Resources channel in Slack | | |
| Exercise | Using the in-class exercise as a guide, answer the same questions but pick one of the visual essays from [The Pudding](https://pudding.cool/). Post your response in the *in-class* channel on Slack. Include the link to the visual essay you chose. |[:link:](http://mdsr-book.github.io/exercises.html#exercise_23) | |
<<<<<<< HEAD
|Reading from R for DS book | Welcome through Section 3.6. Post any questions in the Resources channel. Work through the material in Chapter 3 including the exercises. You can do this by creating an **.Rmd** file and copy/paste directly from the text. Make sure to save this file as something like *ch3_r4ds.Rmd* so that you can use it as a resource later on |[:book:](https://r4ds.had.co.nz/index.html) | |
=======
|Reading from R for DS book | Welcome through Section 3.6. Post any questions in the Resources channel. Work through the material in Chapter 3 including the exercise. You can do this by creating an **.Rmd** file and copy/paste directly from the text. |[:book:](https://r4ds.had.co.nz/index.html) | |
>>>>>>> b85b0a8a3a00af37ad35097cb6103fa56995bb7c
|top 10 do and don't for charts | Optional Reading |[:link:](https://guides.lib.uci.edu/datavis/do) | |
|Calling bs | Optional perusing. This is the course Dr. B mentioned during Wednesday's lecture.  |[:link:](https://www.callingbullshit.org/tools.html)||

