---
title: 'Week 2: Intro to Visualizing Data'
slug: data-viz
weight: 20
draft: false
---


**Grammar of Graphics & ggplot**\
\
This week we will be discussing what qualities makes a graphic legible and how we can use R to implement readability using the Grammar of Graphics.\
\

| Tasks | Notes | Links | Due |
| -------- | ------------- | ------ | ---- |
| | | | |
| Data Viz: intro | Slides | [:link:](/slides/data-viz-intro.html) | |
| Reading from MSDR book | Chapter 2: Data visualization. Post reading response (include one takeaway, one thing that would improve the reading, and any questions that you may have) in the Resources channel in Slack | | |
| In-class example | Write up your response to Supplemental Exercise [Problem 3](http://mdsr-book.github.io/exercises.html#exercise_23)  | | |
|Reading from R for DS book | Section 2.5. Text on Markdown shortcuts. Create an **.Rmd** titled *markdown_basics* and try these commands out using a dataset of your choice (you may use the built-in **iris** data set). |[:book:](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html) | |
|Reading from R for DS book | Section 2.6 (skip 2.6.2: tables). Text on Markdown code chunks and plots. Try these commands out in your *markdown_basics.Rmd* file and then post to the Resources channel in Slack. |[:book:](https://bookdown.org/yihui/rmarkdown/r-code.html) | |
|ggplot flipbook | Slide deck (may not be smart device friendly) |  [:link:](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html#1) | |
|top 10 do and don't for charts | Optional Reading |[:link:](https://guides.lib.uci.edu/datavis/do) | |

